const $=id=>document.getElementById(id);
const names=['Obstacle forward','Obstacle left','Obstacle forward velocity','Obstacle lateral velocity','Obstacle planning radius','Current clearance','Left path clearance','Right path clearance','Back-off clearance','Predicted wait clearance','Goal distance','Heading error'];
const units=['m','m','m/s','m/s','m','m','m','m','m','m','m','rad'];
const skills=['Bypass left','Bypass right','Wait','Back off'];
const colors=['#66bdf6','#ffb16a','#61e7c6','#e68ccb'];
let current=null,snapshot=null,lastId=null,trail=[],lastTime=-1,animation=null,pending=false;
function el(tag,text,cls){const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e}
for(let i=0;i<96;i++){const o=el('option',i<64?'L1 · '+i:'L2 · '+(i-64));o.value=i;$('neuron').append(o)}$('neuron').value=65;
function ctx(id){const c=$(id),w=c.clientWidth,h=c.clientHeight,d=devicePixelRatio||1;c.width=w*d;c.height=h*d;const x=c.getContext('2d');x.scale(d,d);x.font='11px system-ui';x.fillStyle='#a9bfce';return{x,w,h}}
function line(x,points,color,width=1,dash=[]){x.strokeStyle=color;x.lineWidth=width;x.setLineDash(dash);x.beginPath();points.forEach((p,i)=>i?x.lineTo(...p):x.moveTo(...p));x.stroke();x.setLineDash([])}
function dot(x,px,py,r,color){x.fillStyle=color;x.beginPath();x.arc(px,py,r,0,Math.PI*2);x.fill()}
function reset(){clearInterval(animation);animation=null;current=null;lastId=null;trail=[];lastTime=-1;$('choice').textContent='Waiting for an encounter';$('scores').replaceChildren();$('inputs').replaceChildren();$('decisionTime').textContent='The network has not been called.';for(const id of ['reason','mask','spikes','voltage'])$(id).textContent='';for(const id of ['decisionLatency','inferenceLatency'])$(id).textContent='—';$('decisionCount').textContent='NO DECISION YET';$('traceState').textContent='AWAITING DATA';$('replay').disabled=true;$('evidenceText').textContent='Exact readout contributions will appear after a decision.';for(const id of ['circuit','raster','membrane','evidence','map'])ctx(id)}
async function command(action){try{const response=await fetch('/api/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scenario:$('scenario').value,reaction:$('reaction').value,seed:0})});if(!response.ok){const r=await response.json();throw Error(r.error||'Command failed')}if(action==='start')reset()}catch(e){$('status').textContent=e.message}}
for(const action of ['start','pause','resume','stop'])$(action).onclick=()=>command(action);
$('camera').onchange=async()=>{try{const response=await fetch('/api/camera',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({camera:$('camera').value})});if(!response.ok)throw Error('Camera change failed')}catch(e){$('status').textContent=e.message}};
function drawCircuit(){if(!current)return;const {x,w,h}=ctx('circuit'),t=current.analysis.trace,step=+$('step').value-1;
const inputX=12,l1=w*.29,l2=w*.58,out=w*.83,top=45;
// Connections summarize the fully connected layers, not individual synapse weights.
for(const[a,b]of[[inputX+20,l1-12],[l1+w*.18,l2-12],[l2+w*.18,out-8]])line(x,[[a,h/2],[b,h/2]],'#456477',2);
x.fillStyle='#a9bfce';x.fillText('12 inputs',inputX,20);x.fillText('64 neurons',l1-8,20);x.fillText('32 neurons',l2-8,20);x.fillText('4 skills',out-6,20);
t.normalized_inputs.forEach((v,i)=>{const y=top+i*16;x.fillStyle=v>=0?'#66bdf6':'#e68ccb';x.fillRect(inputX,y,Math.max(2,Math.abs(v)*4),8)});
for(let n=0;n<96;n++){const layer=n<64?0:1,index=layer?n-64:n,cx=(layer?l2:l1)+(index%8)*w*.024,cy=top+Math.floor(index/8)*24+10;dot(x,cx,cy,Math.max(2.8,Math.min(5,w*.008)),t.raster[step][n]?'#61e7c6':'#304957');if(n===+$('neuron').value){x.strokeStyle='#ffb16a';x.lineWidth=1.5;x.beginPath();x.arc(cx,cy,7,0,Math.PI*2);x.stroke()}}
current.analysis.scores.forEach((v,i)=>{const y=60+i*47;dot(x,out,y,7,current.analysis.allowed[i]?colors[i]:'#45505e');x.fillStyle=colors[i];x.fillText(['Left','Right','Wait','Back'][i],out+12,y-3);x.fillStyle='#e8f2fa';x.fillText(v.toFixed(2),out+12,y+11)});
$('stepLabel').textContent=(step+1)+' / 16';$('spikes').textContent=t.raster[step].reduce((a,b)=>a+b,0)+' neurons fire at step '+(step+1)+' · '+t.spikes+' spikes across the full decision. Output numbers show final scores.'}
function drawSignals(){if(!current)return;const t=current.analysis.trace,step=+$('step').value-1;drawCircuit();let {x,w,h}=ctx('raster');const left=28,right=w-8,top=10,bottom=h-28;
line(x,[[left+(right-left)*(step+.5)/16,top],[left+(right-left)*(step+.5)/16,bottom]],'#3b6974',8);
t.raster.forEach((r,s)=>r.forEach((v,n)=>{if(v){x.fillStyle=s===step?'#ffffff':'#61e7c6';x.fillRect(left+(right-left)*(s+.2)/16,bottom-(bottom-top)*(n+1)/96,Math.max(2,(right-left)/16*.5),1.5)}}));x.fillStyle='#a9bfce';x.fillText('L2',0,30);x.fillText('L1',0,135);x.fillText('1',left,h-8);x.fillText('16 internal steps',Math.max(left,right-100),h-8);
({x,w,h}=ctx('membrane'));const n=+$('neuron').value,a=t.membrane_before_reset.map(r=>r[n]),b=t.membrane_after_reset.map(r=>r[n]),lo=Math.min(0,...a,...b),hi=Math.max(1.2,...a,...b),X=i=>34+i/15*(w-48),Y=v=>h-25-(v-lo)/(hi-lo)*(h-45);
line(x,[[34,Y(1)],[w-12,Y(1)]],'#a9bfce',1,[4,4]);x.fillStyle='#a9bfce';x.fillText('1',12,Y(1));x.fillText(hi.toFixed(1),0,15);x.fillText(lo.toFixed(1),0,h-25);
for(const[arr,color]of[[a,'#61e7c6'],[b,'#ffb16a']]){line(x,arr.map((v,i)=>[X(i),Y(v)]),color,1.5);dot(x,X(step),Y(arr[step]),4,color)}
$('voltage').textContent=$('neuron').selectedOptions[0].text+' at step '+(step+1)+': before '+a[step].toFixed(3)+' → spike '+t.raster[step][n]+' → after '+b[step].toFixed(3)+'. Soft reset subtracts 1; it does not always reset to zero.'}
function replay(){if(!current)return;clearInterval(animation);$('step').value=1;$('traceState').textContent='SLOWED REPLAY OF LAST DECISION';drawSignals();if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;animation=setInterval(()=>{if(+$('step').value>=16){clearInterval(animation);animation=null;$('traceState').textContent='LAST DECISION HELD';return}$('step').value=+$('step').value+1;drawSignals()},110)}
$('step').oninput=()=>{clearInterval(animation);animation=null;$('traceState').textContent='MANUAL TRACE INSPECTION';drawSignals()};$('replay').onclick=replay;$('neuron').onchange=drawSignals;
function drawEvidence(){if(!current)return;const e=current.analysis.evidence,c=e.comparison,{x,w,h}=ctx('evidence'),values=c?c.per_neuron:e.per_neuron,bias=c?c.bias:e.bias;
const sorted=values.map((v,i)=>({v,label:'L2 neuron '+i})).sort((a,b)=>Math.abs(b.v)-Math.abs(a.v)),display=sorted.slice(0,6);display.push({label:'Other 26 neurons',v:sorted.slice(6).reduce((s,a)=>s+a.v,0)},{label:'Readout bias',v:bias});
const max=Math.max(.1,...display.map(a=>Math.abs(a.v))),left=Math.min(125,w*.36),zero=left+(w-left-45)/2,scale=(w-left-55)/2/max;
line(x,[[zero,4],[zero,h-12]],'#526d7f');display.forEach((a,i)=>{const y=17+i*27;x.fillStyle='#a9bfce';x.fillText(a.label,0,y+3);x.fillStyle=a.v>=0?'#61e7c6':'#e68ccb';x.fillRect(Math.min(zero,zero+a.v*scale),y-7,Math.max(1,Math.abs(a.v*scale)),12);x.fillStyle='#edf5fa';const text=(a.v>=0?'+':'')+a.v.toFixed(2);x.fillText(text,w-38,y+3)});
$('evidenceText').textContent=c?skills[e.skill]+' versus '+skills[e.runner]+': margin '+c.margin.toFixed(2)+'. Positive contributions favor the selected skill; negative contributions favor its best allowed alternative. Bars plus bias sum to the margin.':skills[e.skill]+' score decomposition. No other skill is allowed; the safety mask determines eligibility. Bars plus bias sum to its raw score.'}
function updateDecision(d){current=d;lastId=d.id;const e=d.event,a=d.analysis;$('choice').textContent=a.selected===null?'No allowed skill':skills[a.selected];$('decisionCount').textContent='DECISION '+d.id.split(':')[1];$('scores').replaceChildren();a.scores.forEach((v,i)=>{const card=el('div','','score'+(a.selected===i?' selected':'')+(!a.allowed[i]?' blocked':''));card.append(el('span',skills[i]),el('strong',v.toFixed(2)),el('small',a.allowed[i]?'ALLOWED':'MASKED'));$('scores').append(card)});
$('reason').textContent=(e.obstacle_name?'Hazard: '+e.obstacle_name.replaceAll('_',' ')+' ('+e.obstacle_shape+'). ':'')+e.reason+'.';$('mask').textContent='Raw preference: '+skills[a.preference]+'. '+(a.preference===a.selected?'The preferred skill passes the geometric mask.':'The mask overrides the raw preference.');$('decisionLatency').textContent=e.decision_ms?.toFixed(2)+' ms';$('inferenceLatency').textContent=e.inference_ms?.toFixed(2)+' ms';$('replay').disabled=false;
const ranking=a.sensitivity.map((s,i)=>({i,v:Math.max(...s.low.delta_scores.map(Math.abs),...s.high.delta_scores.map(Math.abs))})).sort((a,b)=>b.v-a.v),max=Math.max(.01,...ranking.map(r=>r.v));$('inputs').replaceChildren();ranking.forEach(({i,v})=>{const row=document.createElement('tr'),measure=el('td',v.toFixed(2),'value'),bar=el('div','','bar'),fill=document.createElement('i');fill.style.width=(v/max*100)+'%';bar.append(fill);measure.append(bar);row.append(el('td',names[i]),el('td',e.features[i].toFixed(3)+' '+units[i],'value'),measure);$('inputs').append(row)});$('decisionPanel').classList.remove('flash');void $('decisionPanel').offsetWidth;$('decisionPanel').classList.add('flash');drawEvidence();replay()}
function drawMap(){if(!snapshot?.row||!snapshot.arena)return;const {x,w,h}=ctx('map'),a=snapshot.arena,r=snapshot.row,[x0,x1,y0,y1]=a.bounds,k=Math.min((w-28)/(x1-x0),(h-28)/(y1-y0)),ox=(w-k*(x1-x0))/2,oy=(h-k*(y1-y0))/2,P=p=>[ox+(p[0]-x0)*k,h-oy-(p[1]-y0)*k];
x.strokeStyle='#456477';x.strokeRect(ox,oy,(x1-x0)*k,(y1-y0)*k);for(let i=Math.ceil(x0);i<x1;i++)line(x,[P([i,y0]),P([i,y1])],'#203847');for(let j=Math.ceil(y0);j<y1;j++)line(x,[P([x0,j]),P([x1,j])],'#203847');
a.obstacles.forEach((o,i)=>{const p=r.obstacle_positions[i],q=P(p);x.save();x.translate(...q);x.rotate(-o.yaw);x.fillStyle=o.moving?'#b75c9d':o.shape==='box'?'#357ba6':'#b7793d';if(o.shape==='box')x.fillRect(-o.half_extents[0]*k,-o.half_extents[1]*k,2*o.half_extents[0]*k,2*o.half_extents[1]*k);else{ x.beginPath();x.arc(0,0,o.radius*k,0,Math.PI*2);x.fill()}x.setLineDash([3,3]);x.strokeStyle='#94a4b5';x.beginPath();x.arc(0,0,o.radius*k,0,Math.PI*2);x.stroke();x.restore()});
if(current?.event.candidate_paths){const e=current.event;e.candidate_paths.forEach((path,i)=>{if(!path.length)return;line(x,[e.selection_position,...path].map(P),colors[i],current.analysis.selected===i?2.5:1,current.analysis.allowed[i]?[]:[3,5])})}
if(trail.length>1)line(x,trail.map(P),'#61e7c6',2);dot(x,...P(a.goal),5,'#ffd060');dot(x,...P([r.x,r.y]),5,'#ffffff');if(r.selected_target)dot(x,...P(r.selected_target),3,'#ffffff');const q=P([r.x,r.y]);line(x,[q,[q[0]+12*Math.cos(r.yaw),q[1]-12*Math.sin(r.yaw)]],'#61e7c6',2);x.fillStyle='#a9bfce';x.fillText('Goal',P(a.goal)[0]-12,P(a.goal)[1]-10)}
function renderState(s){snapshot=s;const active=['starting','running','paused'].includes(s.status);$('status').textContent=s.status==='error'?s.error:s.status;$('status').className=s.status==='error'?'error':'tag';$('start').disabled=active;$('scenario').disabled=active;$('reaction').disabled=active;$('pause').disabled=s.status!=='running';$('resume').disabled=s.status!=='paused';$('stop').disabled=!active;
if(s.frame)$('video').src='data:image/jpeg;base64,'+s.frame;if(s.options){$('courseLabel').textContent=s.options.scenario.replaceAll('_',' ').toUpperCase();$('senseInterval').textContent=s.sensing_ms+' ms';$('confirmation').textContent=s.confirmation_ms+' ms'}
if(s.row){const r=s.row;if(r.time<lastTime)trail=[];if(r.time!==lastTime){trail.push([r.x,r.y]);if(trail.length>3000)trail.shift();lastTime=r.time}$('time').textContent=r.time.toFixed(1)+' s';$('distance').textContent=r.distance.toFixed(2)+' m';$('speed').textContent=r.speed.toFixed(3)+' m/s';$('torque').textContent=r.torque.toFixed(1)+' Nm';$('state').textContent=r.state+(r.skill?' · '+r.skill.replaceAll('_',' '):'');$('motionText').textContent=r.skill==='wait'?'Standing while a moving hazard clears; joint PID remains active.':r.state==='RECOVER'?'Settling the gait before returning to goal tracking.':'Tracking the current target with the classical gait and joint PID.';$('commands').textContent='Body command: forward '+r.command_vx.toFixed(3)+' m/s · lateral '+r.command_vy.toFixed(3)+' m/s · yaw '+r.command_yaw_rate.toFixed(3)+' rad/s';$('playback').textContent=s.playback_speed;$('flowSkill').className=r.state==='SKILL'?'active':'';$('flowPid').className=s.status==='running'?'active':'';$('flowSnn').className=current&&r.time-current.event.time<.2?'active':'';if(current)$('decisionTime').textContent='Selected at '+current.event.time.toFixed(2)+' s · '+Math.max(0,r.time-current.event.time).toFixed(2)+' s ago. Trace held until the next selection.';drawMap()}
if(s.timeline){$('timeline').replaceChildren();s.timeline.slice(-8).reverse().forEach(e=>{const item=document.createElement('li');item.append(el('time',e.time.toFixed(1)+' s'),el('span',e.target+(e.skill?' · '+e.skill.replaceAll('_',' '):'')+' — '+e.reason));$('timeline').append(item)})}
if(s.summary){$('state').textContent=s.summary.reason;$('motionText').textContent='Final error '+s.summary.final_distance.toFixed(3)+' m · collision: '+s.summary.collision+' · fall: '+s.summary.fall+'. Episode saved; restart to replay.'}}
async function poll(){if(pending)return;pending=true;try{const response=await fetch('/api/state');if(!response.ok)throw Error('Cannot read simulation');const s=await response.json();if(!s.decision_id&&current&&s.row&&s.row.time<lastTime)reset();if(s.decision_id&&s.decision_id!==lastId){const d=await(await fetch('/api/decision')).json();if(d?.id!==s.decision_id)return;updateDecision(d)}renderState(s)}catch(e){$('status').textContent='Connection lost: '+e.message}finally{pending=false;setTimeout(poll,100)}}
window.addEventListener('resize',()=>{drawSignals();drawEvidence();drawMap()});poll();
